G_kitchen_objtype = ['StoveBurner','Drawer','CounterTop','Cabinet','StoveKnob','Window','Sink','Floor','Book','Bottle','Knife','Microwave','Bread','Fork','Shelf','Potato','HousePlant','Toaster','SoapBottle','Kettle','Pan','Plate','Tomato','Vase','GarbageCan','Egg','CreditCard','WineBottle','Pot','Spatula','PaperTowelRoll','Cup','Fridge','CoffeeMachine','Bowl','SinkBasin','SaltShaker','PepperShaker','Lettuce','ButterKnife','Apple','DishSponge','Spoon','LightSwitch','Mug','ShelvingUnit','Statue','Stool','Faucet','Ladle','CellPhone','Chair','SideTable','DiningTable','Pen','SprayBottle','Curtains','Pencil','Blinds','GarbageBag','Safe','Mirror','AluminumFoil']

G_livingroom_objtype = ['Floor', 'Painting', 'Book', 'Box', 'Curtains', 'Statue', 'Laptop', 'Television', 'HousePlant', 'TissueBox', 'CreditCard', 'Plate', 'KeyChain', 'GarbageCan', 'FloorLamp', 'Vase', 'DeskLamp', 'Pencil', 'Pillow', 'Bowl', 'RemoteControl', 'Watch', 'Pen', 'Newspaper', 'Window', 'LightSwitch', 'SideTable', 'Drawer', 'ArmChair', 'DiningTable', 'CoffeeTable', 'Shelf', 'TVStand', 'Sofa', 'Chair', 'WateringCan', 'Boots', 'CellPhone', 'Ottoman', 'Desk', 'Safe', 'Dresser', 'Cabinet', 'ShelvingUnit', 'Mirror', 'DogBed', 'Candle', 'RoomDecor', 'Stool', 'Blinds']

G_bedroom_objtype = ['Floor', 'Book', 'Box', 'Bed', 'Laptop', 'CellPhone', 'BaseballBat', 'DeskLamp', 'BasketBall', 'TissueBox', 'CreditCard', 'GarbageCan', 'AlarmClock', 'Pencil', 'Boots', 'Blinds', 'Pillow', 'KeyChain', 'Bowl', 'Watch', 'Mirror', 'CD', 'Pen', 'Window', 'LightSwitch', 'Chair', 'Mug', 'Shelf', 'DogBed', 'Drawer', 'Dresser', 'Statue', 'Desk', 'HousePlant', 'TennisRacket', 'TeddyBear', 'Painting', 'SideTable', 'Safe', 'Vase', 'Poster', 'Cloth', 'Dumbbell', 'GarbageBag', 'ShelvingUnit', 'LaundryHamper', 'Television', 'RemoteControl', 'Cabinet', 'ArmChair', 'CounterTop', 'CoffeeTable', 'TableTopDecor', 'Desktop', 'Stool', 'Curtains', 'Footstool', 'Sofa', 'VacuumCleaner']

G_bathroom_objtype = ['Faucet', 'Window', 'BathtubBasin', 'ShowerCurtain', 'Floor', 'ShowerHead', 'Bathtub', 'Mirror', 'Towel', 'HandTowel', 'Plunger', 'TowelHolder', 'ToiletPaperHanger', 'SoapBar', 'ToiletPaper', 'SoapBottle', 'Shelf', 'GarbageCan', 'HandTowelHolder', 'Cloth', 'PaperTowelRoll', 'Candle', 'SprayBottle', 'ScrubBrush', 'DishSponge', 'Toilet', 'LightSwitch', 'Sink', 'SinkBasin', 'SideTable', 'Cabinet', 'ShowerGlass', 'ShowerDoor', 'CounterTop', 'TissueBox', 'Drawer', 'Dresser', 'HousePlant', 'Painting', 'Footstool']

G_action2code = {"MoveAhead": 0, "RotateLeft":1, "RotateRight":2, "LookUp":3, "LookDown":4, "Done":5}
G_action_code2action = {v:k for (k, v) in G_action2code.items()}